export default {
    THEME_CHANGE: Symbol('THEME_CHANGE'),
    THEME_INIT: Symbol('THEME_INIT'),
    POPULAR_REFRESH: Symbol('POPULAR_REFRESH'),
    POPULAR_REFRESH_FAIL: Symbol('LOAD_POPULAR_FAIL'),
    POPULAR_REFRESH_SUCCESS: Symbol('LOAD_POPULAR_SUCCESS'),
    POPULAR_LOAD_MORE_SUCCESS: Symbol('POPULAR_LOAD_MORE_SUCCESS'),
    POPULAR_LOAD_MORE_FAIL: Symbol('POPULAR_LOAD_MORE_FAIL'),
};
