export default {
    THEME_CHANGE: Symbol('THEME_CHANGE'),
    THEME_INIT: Symbol('THEME_INIT'),
    POPULAR_REFRESH: Symbol('POPULAR_REFRESH'),
    LOAD_POPULAR_FAIL: Symbol('LOAD_POPULAR_FAIL'),
    LOAD_POPULAR_SUCCESS: Symbol('LOAD_POPULAR_SUCCESS'),
};
