export default {
    THEME_CHANGE: Symbol('THEME_CHANGE'),
    THEME_INIT: Symbol('THEME_INIT'),
    POPULAR_REFRESH: Symbol('POPULAR_REFRESH'),
    POPULAR_REFRESH_FAIL: Symbol('POPULAR_REFRESH_FAIL'),
    POPULAR_REFRESH_SUCCESS: Symbol('POPULAR_REFRESH_SUCCESS'),
    POPULAR_LOAD_MORE_SUCCESS: Symbol('POPULAR_LOAD_MORE_SUCCESS'),
    POPULAR_LOAD_MORE_FAIL: Symbol('POPULAR_LOAD_MORE_FAIL'),
    TRENDING_REFRESH: Symbol('TRENDING_REFRESH'),
    TRENDING_REFRESH_FAIL: Symbol('TRENDING_REFRESH_FAIL'),
    TRENDING_REFRESH_SUCCESS: Symbol('TRENDING_REFRESH_SUCCESS'),
    TRENDING_LOAD_MORE_SUCCESS: Symbol('TRENDING_LOAD_MORE_SUCCESS'),
    TRENDING_LOAD_MORE_FAIL: Symbol('TRENDING_LOAD_MORE_FAIL'),
};
